// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTagToVideo(videoID: string, tagID: number): $CancellablePromise<void> {
    return $Call.ByID(3342648587, videoID, tagID);
}

export function AddVideoToCollection(collectionID: number, videoID: string): $CancellablePromise<void> {
    return $Call.ByID(3240115, collectionID, videoID);
}

export function AutoSummarizePending(): $CancellablePromise<number> {
    return $Call.ByID(467400847);
}

export function AutoTagVideo(videoID: string, provider: string, model: string, baseURL: string, apiKey: string, temperature: number): $CancellablePromise<$models.AutoTagResult> {
    return $Call.ByID(1826636284, videoID, provider, model, baseURL, apiKey, temperature).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateCollection(input: $models.CollectionInput): $CancellablePromise<models$0.Collection> {
    return $Call.ByID(1043294992, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateTag(input: $models.TagInput): $CancellablePromise<models$0.Tag> {
    return $Call.ByID(2870908676, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteChannel(channelID: string): $CancellablePromise<void> {
    return $Call.ByID(483603834, channelID);
}

export function DeleteCollection(id: number): $CancellablePromise<void> {
    return $Call.ByID(2175291787, id);
}

export function DeleteTag(id: number): $CancellablePromise<void> {
    return $Call.ByID(3987509489, id);
}

export function DeleteTemplate(name: string): $CancellablePromise<void> {
    return $Call.ByID(2630527809, name);
}

export function ExportBackup(): $CancellablePromise<$models.BackupRestoreResult> {
    return $Call.ByID(2386572392).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExportCollectionMarkdown(collectionID: number): $CancellablePromise<string> {
    return $Call.ByID(3456935715, collectionID);
}

export function ExportCollectionPDF(collectionID: number): $CancellablePromise<string> {
    return $Call.ByID(2752699868, collectionID);
}

export function ExportTemplates(): $CancellablePromise<string> {
    return $Call.ByID(2109904041);
}

export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(575209370).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSyncSettings(): $CancellablePromise<$models.SyncSettings> {
    return $Call.ByID(2693712682).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Health(): $CancellablePromise<string> {
    return $Call.ByID(1376490622);
}

export function ImportBackup(path: string, restoreDB: boolean): $CancellablePromise<$models.BackupRestoreResult> {
    return $Call.ByID(3006488463, path, restoreDB).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportTemplates(raw: string, overwrite: boolean): $CancellablePromise<$models.TemplateImportResult> {
    return $Call.ByID(1326721144, raw, overwrite).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListChannels(): $CancellablePromise<models$0.Channel[]> {
    return $Call.ByID(1848224760).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListCollectionVideos(collectionID: number): $CancellablePromise<$models.VideoItem[]> {
    return $Call.ByID(1569885708, collectionID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListCollections(): $CancellablePromise<$models.CollectionItem[]> {
    return $Call.ByID(3685511405).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListTags(): $CancellablePromise<models$0.Tag[]> {
    return $Call.ByID(1202323897).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListTemplates(): $CancellablePromise<models$0.Template[]> {
    return $Call.ByID(1283993515).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListVideos(limit: number, offset: number, filter: $models.VideoFilter): $CancellablePromise<$models.VideoItem[]> {
    return $Call.ByID(1380744448, limit, offset, filter).then(($result: any) => {
        return $$createType10($result);
    });
}

export function LogClientError(message: string): $CancellablePromise<void> {
    return $Call.ByID(2350793085, message);
}

export function RemoveTagFromVideo(videoID: string, tagID: number): $CancellablePromise<void> {
    return $Call.ByID(2432871971, videoID, tagID);
}

export function RemoveVideoFromCollection(collectionID: number, videoID: string): $CancellablePromise<void> {
    return $Call.ByID(3305569103, collectionID, videoID);
}

export function ResetDefaultTemplates(): $CancellablePromise<void> {
    return $Call.ByID(224324571);
}

export function SaveAppSettings(input: $models.AppSettingsInput): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3027434097, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SaveTemplate(input: $models.TemplateInput): $CancellablePromise<models$0.Template> {
    return $Call.ByID(109214187, input).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SeedDefaultTemplates(): $CancellablePromise<void> {
    return $Call.ByID(2993909729);
}

export function SummarizeText(req: $models.SummarizeRequest): $CancellablePromise<string> {
    return $Call.ByID(3634329554, req);
}

export function SummarizeVideo(videoID: string, templateName: string, provider: string, model: string, baseURL: string, apiKey: string, temperature: number): $CancellablePromise<string> {
    return $Call.ByID(2613629376, videoID, templateName, provider, model, baseURL, apiKey, temperature);
}

export function SyncAllChannels(): $CancellablePromise<$models.SyncSummary> {
    return $Call.ByID(3774921414).then(($result: any) => {
        return $$createType16($result);
    });
}

export function SyncChannelFeed(channelID: string): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(2298211314, channelID).then(($result: any) => {
        return $$createType17($result);
    });
}

export function UpdateSyncSettings(input: $models.SyncSettingsInput): $CancellablePromise<$models.SyncSettings> {
    return $Call.ByID(4254994483, input).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AutoTagResult.createFrom;
const $$createType1 = models$0.Collection.createFrom;
const $$createType2 = models$0.Tag.createFrom;
const $$createType3 = $models.BackupRestoreResult.createFrom;
const $$createType4 = $models.AppSettings.createFrom;
const $$createType5 = $models.SyncSettings.createFrom;
const $$createType6 = $models.TemplateImportResult.createFrom;
const $$createType7 = models$0.Channel.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.VideoItem.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.CollectionItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType2);
const $$createType14 = models$0.Template.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SyncSummary.createFrom;
const $$createType17 = $models.SyncResult.createFrom;
