// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export class AppSettings {
    "LLMProvider": string;
    "OpenAIKey": string;
    "OpenAIModel": string;
    "OllamaURL": string;
    "ResponseLanguage": string;
    "SelectedTemplate": string;
    "AutoSyncEnabled": boolean;
    "SyncIntervalMinutes": number;
    "NotificationsEnabled": boolean;
    "AutoSummaryEnabled": boolean;
    "SummaryIntervalMinutes": number;
    "SummaryBatchSize": number;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("LLMProvider" in $$source)) {
            this["LLMProvider"] = "";
        }
        if (!("OpenAIKey" in $$source)) {
            this["OpenAIKey"] = "";
        }
        if (!("OpenAIModel" in $$source)) {
            this["OpenAIModel"] = "";
        }
        if (!("OllamaURL" in $$source)) {
            this["OllamaURL"] = "";
        }
        if (!("ResponseLanguage" in $$source)) {
            this["ResponseLanguage"] = "";
        }
        if (!("SelectedTemplate" in $$source)) {
            this["SelectedTemplate"] = "";
        }
        if (!("AutoSyncEnabled" in $$source)) {
            this["AutoSyncEnabled"] = false;
        }
        if (!("SyncIntervalMinutes" in $$source)) {
            this["SyncIntervalMinutes"] = 0;
        }
        if (!("NotificationsEnabled" in $$source)) {
            this["NotificationsEnabled"] = false;
        }
        if (!("AutoSummaryEnabled" in $$source)) {
            this["AutoSummaryEnabled"] = false;
        }
        if (!("SummaryIntervalMinutes" in $$source)) {
            this["SummaryIntervalMinutes"] = 0;
        }
        if (!("SummaryBatchSize" in $$source)) {
            this["SummaryBatchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class AppSettingsInput {
    "LLMProvider": string;
    "OpenAIKey": string;
    "OpenAIModel": string;
    "OllamaURL": string;
    "ResponseLanguage": string;
    "SelectedTemplate": string;
    "AutoSyncEnabled": boolean;
    "SyncIntervalMinutes": number;
    "NotificationsEnabled": boolean;
    "AutoSummaryEnabled": boolean;
    "SummaryIntervalMinutes": number;
    "SummaryBatchSize": number;

    /** Creates a new AppSettingsInput instance. */
    constructor($$source: Partial<AppSettingsInput> = {}) {
        if (!("LLMProvider" in $$source)) {
            this["LLMProvider"] = "";
        }
        if (!("OpenAIKey" in $$source)) {
            this["OpenAIKey"] = "";
        }
        if (!("OpenAIModel" in $$source)) {
            this["OpenAIModel"] = "";
        }
        if (!("OllamaURL" in $$source)) {
            this["OllamaURL"] = "";
        }
        if (!("ResponseLanguage" in $$source)) {
            this["ResponseLanguage"] = "";
        }
        if (!("SelectedTemplate" in $$source)) {
            this["SelectedTemplate"] = "";
        }
        if (!("AutoSyncEnabled" in $$source)) {
            this["AutoSyncEnabled"] = false;
        }
        if (!("SyncIntervalMinutes" in $$source)) {
            this["SyncIntervalMinutes"] = 0;
        }
        if (!("NotificationsEnabled" in $$source)) {
            this["NotificationsEnabled"] = false;
        }
        if (!("AutoSummaryEnabled" in $$source)) {
            this["AutoSummaryEnabled"] = false;
        }
        if (!("SummaryIntervalMinutes" in $$source)) {
            this["SummaryIntervalMinutes"] = 0;
        }
        if (!("SummaryBatchSize" in $$source)) {
            this["SummaryBatchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettingsInput($$parsedSource as Partial<AppSettingsInput>);
    }
}

export class AutoTagResult {
    "Tags": models$0.Tag[];
    "Raw": string;

    /** Creates a new AutoTagResult instance. */
    constructor($$source: Partial<AutoTagResult> = {}) {
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Raw" in $$source)) {
            this["Raw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoTagResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoTagResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField0_0($$parsedSource["Tags"]);
        }
        return new AutoTagResult($$parsedSource as Partial<AutoTagResult>);
    }
}

export class BackupRestoreResult {
    "BackupPath": string;
    "RestoredDB": string;
    "ImportedTemplates": number;

    /** Creates a new BackupRestoreResult instance. */
    constructor($$source: Partial<BackupRestoreResult> = {}) {
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = "";
        }
        if (!("RestoredDB" in $$source)) {
            this["RestoredDB"] = "";
        }
        if (!("ImportedTemplates" in $$source)) {
            this["ImportedTemplates"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupRestoreResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupRestoreResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupRestoreResult($$parsedSource as Partial<BackupRestoreResult>);
    }
}

export class CollectionInput {
    "Name": string;
    "Description": string;

    /** Creates a new CollectionInput instance. */
    constructor($$source: Partial<CollectionInput> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CollectionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectionInput($$parsedSource as Partial<CollectionInput>);
    }
}

export class CollectionItem {
    "ID": number;
    "Name": string;
    "Description": string;
    "VideoCount": number;

    /** Creates a new CollectionItem instance. */
    constructor($$source: Partial<CollectionItem> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("VideoCount" in $$source)) {
            this["VideoCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CollectionItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectionItem($$parsedSource as Partial<CollectionItem>);
    }
}

export class SummarizeRequest {
    "Text": string;
    "TemplateName": string;
    "Provider": string;
    "Model": string;
    "BaseURL": string;
    "APIKey": string;
    "Temperature": number;
    "Title": string;
    "Channel": string;
    "Duration": string;
    "KeyPoints": string;

    /** Creates a new SummarizeRequest instance. */
    constructor($$source: Partial<SummarizeRequest> = {}) {
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("TemplateName" in $$source)) {
            this["TemplateName"] = "";
        }
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("BaseURL" in $$source)) {
            this["BaseURL"] = "";
        }
        if (!("APIKey" in $$source)) {
            this["APIKey"] = "";
        }
        if (!("Temperature" in $$source)) {
            this["Temperature"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Channel" in $$source)) {
            this["Channel"] = "";
        }
        if (!("Duration" in $$source)) {
            this["Duration"] = "";
        }
        if (!("KeyPoints" in $$source)) {
            this["KeyPoints"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummarizeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SummarizeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SummarizeRequest($$parsedSource as Partial<SummarizeRequest>);
    }
}

export class SyncResult {
    "ChannelID": string;
    "ChannelName": string;
    "NewVideos": number;
    "UpdatedVideos": number;

    /** Creates a new SyncResult instance. */
    constructor($$source: Partial<SyncResult> = {}) {
        if (!("ChannelID" in $$source)) {
            this["ChannelID"] = "";
        }
        if (!("ChannelName" in $$source)) {
            this["ChannelName"] = "";
        }
        if (!("NewVideos" in $$source)) {
            this["NewVideos"] = 0;
        }
        if (!("UpdatedVideos" in $$source)) {
            this["UpdatedVideos"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResult($$parsedSource as Partial<SyncResult>);
    }
}

export class SyncSettings {
    "Enabled": boolean;
    "IntervalMinutes": number;
    "NotificationsEnabled": boolean;

    /** Creates a new SyncSettings instance. */
    constructor($$source: Partial<SyncSettings> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("IntervalMinutes" in $$source)) {
            this["IntervalMinutes"] = 0;
        }
        if (!("NotificationsEnabled" in $$source)) {
            this["NotificationsEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncSettings($$parsedSource as Partial<SyncSettings>);
    }
}

export class SyncSettingsInput {
    "Enabled": boolean;
    "IntervalMinutes": number;
    "NotificationsEnabled": boolean;

    /** Creates a new SyncSettingsInput instance. */
    constructor($$source: Partial<SyncSettingsInput> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("IntervalMinutes" in $$source)) {
            this["IntervalMinutes"] = 0;
        }
        if (!("NotificationsEnabled" in $$source)) {
            this["NotificationsEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncSettingsInput($$parsedSource as Partial<SyncSettingsInput>);
    }
}

export class SyncSummary {
    "TotalNew": number;
    "TotalUpdated": number;
    "Channels": SyncResult[];

    /** Creates a new SyncSummary instance. */
    constructor($$source: Partial<SyncSummary> = {}) {
        if (!("TotalNew" in $$source)) {
            this["TotalNew"] = 0;
        }
        if (!("TotalUpdated" in $$source)) {
            this["TotalUpdated"] = 0;
        }
        if (!("Channels" in $$source)) {
            this["Channels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSummary {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Channels" in $$parsedSource) {
            $$parsedSource["Channels"] = $$createField2_0($$parsedSource["Channels"]);
        }
        return new SyncSummary($$parsedSource as Partial<SyncSummary>);
    }
}

export class TagInput {
    "Name": string;
    "Color": string;
    "AutoGenerated": boolean;

    /** Creates a new TagInput instance. */
    constructor($$source: Partial<TagInput> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Color" in $$source)) {
            this["Color"] = "";
        }
        if (!("AutoGenerated" in $$source)) {
            this["AutoGenerated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TagInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagInput($$parsedSource as Partial<TagInput>);
    }
}

export class TemplateImportResult {
    "Imported": number;
    "Skipped": number;

    /** Creates a new TemplateImportResult instance. */
    constructor($$source: Partial<TemplateImportResult> = {}) {
        if (!("Imported" in $$source)) {
            this["Imported"] = 0;
        }
        if (!("Skipped" in $$source)) {
            this["Skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateImportResult($$parsedSource as Partial<TemplateImportResult>);
    }
}

export class TemplateInput {
    "Name": string;
    "Description": string;
    "Prompt": string;
    "Variables": string;
    "IsDefault": boolean;
    "CreatedBy": string;

    /** Creates a new TemplateInput instance. */
    constructor($$source: Partial<TemplateInput> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Prompt" in $$source)) {
            this["Prompt"] = "";
        }
        if (!("Variables" in $$source)) {
            this["Variables"] = "";
        }
        if (!("IsDefault" in $$source)) {
            this["IsDefault"] = false;
        }
        if (!("CreatedBy" in $$source)) {
            this["CreatedBy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateInput($$parsedSource as Partial<TemplateInput>);
    }
}

export class VideoFilter {
    "ChannelID": string;
    "TagID": number;
    "Query": string;

    /** Creates a new VideoFilter instance. */
    constructor($$source: Partial<VideoFilter> = {}) {
        if (!("ChannelID" in $$source)) {
            this["ChannelID"] = "";
        }
        if (!("TagID" in $$source)) {
            this["TagID"] = 0;
        }
        if (!("Query" in $$source)) {
            this["Query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoFilter($$parsedSource as Partial<VideoFilter>);
    }
}

export class VideoItem {
    "ID": number;
    "VideoID": string;
    "Title": string;
    "URL": string;
    "ChannelID": number;
    "ChannelName": string;
    "Thumbnail": string;
    "Summary": string;
    "Transcript": string;
    "TranscriptStatus": string;
    "TranscriptLastError": string;
    "TranscriptLastAttempt": time$0.Time | null;
    "PublishedAt": time$0.Time;

    /** Creates a new VideoItem instance. */
    constructor($$source: Partial<VideoItem> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("VideoID" in $$source)) {
            this["VideoID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("ChannelID" in $$source)) {
            this["ChannelID"] = 0;
        }
        if (!("ChannelName" in $$source)) {
            this["ChannelName"] = "";
        }
        if (!("Thumbnail" in $$source)) {
            this["Thumbnail"] = "";
        }
        if (!("Summary" in $$source)) {
            this["Summary"] = "";
        }
        if (!("Transcript" in $$source)) {
            this["Transcript"] = "";
        }
        if (!("TranscriptStatus" in $$source)) {
            this["TranscriptStatus"] = "";
        }
        if (!("TranscriptLastError" in $$source)) {
            this["TranscriptLastError"] = "";
        }
        if (!("TranscriptLastAttempt" in $$source)) {
            this["TranscriptLastAttempt"] = null;
        }
        if (!("PublishedAt" in $$source)) {
            this["PublishedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoItem instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoItem($$parsedSource as Partial<VideoItem>);
    }
}

// Private type creation functions
const $$createType0 = models$0.Tag.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SyncResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
