package models

import "time"

type Tag struct {
	ID            uint   `gorm:"primaryKey"`
	Name          string `gorm:"uniqueIndex"`
	Color         string
	AutoGenerated bool
	Videos        []Video `gorm:"many2many:video_tags;"`
	CreatedAt     time.Time
}
