// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Channel {
    "ID": number;
    "ChannelID": string;
    "Name": string;
    "URL": string;
    "Thumbnail": string;
    "Description": string;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Channel instance. */
    constructor($$source: Partial<Channel> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("ChannelID" in $$source)) {
            this["ChannelID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Thumbnail" in $$source)) {
            this["Thumbnail"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Channel instance from a string or object.
     */
    static createFrom($$source: any = {}): Channel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Channel($$parsedSource as Partial<Channel>);
    }
}

export class Collection {
    "ID": number;
    "Name": string;
    "Description": string;
    "Videos": Video[];
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Collection instance. */
    constructor($$source: Partial<Collection> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Videos" in $$source)) {
            this["Videos"] = [];
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     */
    static createFrom($$source: any = {}): Collection {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Videos" in $$parsedSource) {
            $$parsedSource["Videos"] = $$createField3_0($$parsedSource["Videos"]);
        }
        return new Collection($$parsedSource as Partial<Collection>);
    }
}

export class Tag {
    "ID": number;
    "Name": string;
    "Color": string;
    "AutoGenerated": boolean;
    "Videos": Video[];
    "CreatedAt": time$0.Time;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Color" in $$source)) {
            this["Color"] = "";
        }
        if (!("AutoGenerated" in $$source)) {
            this["AutoGenerated"] = false;
        }
        if (!("Videos" in $$source)) {
            this["Videos"] = [];
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Videos" in $$parsedSource) {
            $$parsedSource["Videos"] = $$createField4_0($$parsedSource["Videos"]);
        }
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

export class Template {
    "ID": number;
    "Name": string;
    "Description": string;
    "Prompt": string;
    "Variables": string;
    "IsDefault": boolean;
    "CreatedBy": string;
    "CreatedAt": time$0.Time;

    /** Creates a new Template instance. */
    constructor($$source: Partial<Template> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Prompt" in $$source)) {
            this["Prompt"] = "";
        }
        if (!("Variables" in $$source)) {
            this["Variables"] = "";
        }
        if (!("IsDefault" in $$source)) {
            this["IsDefault"] = false;
        }
        if (!("CreatedBy" in $$source)) {
            this["CreatedBy"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     */
    static createFrom($$source: any = {}): Template {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Template($$parsedSource as Partial<Template>);
    }
}

export class Video {
    "ID": number;
    "VideoID": string;
    "Title": string;
    "URL": string;
    "ChannelID": number;
    "Transcript": string;
    "TranscriptStatus": string;
    "TranscriptLastError": string;
    "TranscriptLastAttempt": time$0.Time | null;
    "Summary": string;
    "Thumbnail": string;
    "PublishedAt": time$0.Time;
    "Tags": Tag[];
    "Collections": Collection[];
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Video instance. */
    constructor($$source: Partial<Video> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("VideoID" in $$source)) {
            this["VideoID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("ChannelID" in $$source)) {
            this["ChannelID"] = 0;
        }
        if (!("Transcript" in $$source)) {
            this["Transcript"] = "";
        }
        if (!("TranscriptStatus" in $$source)) {
            this["TranscriptStatus"] = "";
        }
        if (!("TranscriptLastError" in $$source)) {
            this["TranscriptLastError"] = "";
        }
        if (!("TranscriptLastAttempt" in $$source)) {
            this["TranscriptLastAttempt"] = null;
        }
        if (!("Summary" in $$source)) {
            this["Summary"] = "";
        }
        if (!("Thumbnail" in $$source)) {
            this["Thumbnail"] = "";
        }
        if (!("PublishedAt" in $$source)) {
            this["PublishedAt"] = null;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Collections" in $$source)) {
            this["Collections"] = [];
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Video instance from a string or object.
     */
    static createFrom($$source: any = {}): Video {
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField12_0($$parsedSource["Tags"]);
        }
        if ("Collections" in $$parsedSource) {
            $$parsedSource["Collections"] = $$createField13_0($$parsedSource["Collections"]);
        }
        return new Video($$parsedSource as Partial<Video>);
    }
}

// Private type creation functions
const $$createType0 = Video.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Tag.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Collection.createFrom;
const $$createType5 = $Create.Array($$createType4);
